### ISSUE TITLE
what is the login and password for precise64 VM?

### ISSUE THREAD

**Issue by ishankaronline** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#106]
Finally I was able to bring up the VM on my windows machine. But it does not login - it is asking for username and password. Where will I find it?

Thanks!
-Shankar

**Comment by allinonebenin** [comment]
Yes, you can use VMware. Read here : https://www.vagrantup.com/docs/vmware/boxes.html

**Comment by odd-snail** [comment]
We can use Vagrant ssh , but still how to login via UI , where it is asking for username and password

**Comment by vccabral** [comment]
The default username and password are both vagrant if someone else find this useful.

**Comment by wampin** [comment]
> Finally I was able to bring up the VM on my windows machine. But it does not login - it is asking for username and password. Where will I find it?
> 
> Thanks!
> -Shankar

I tried 'vagrant' on a whim, and it worked for me

**Comment by allinonebenin** [comment]
Cris said it :
The default username and password are both vagrant 

INFO | ALL IN ONE-BENIN
Business Hours : Mon.-Fri. 8:30-5:30pm & Saturday 9-3pm
Direction : 1st street on right after CrossRoad Houeyiho, “Houeyiho”, Lot 1093 Villa Awussi
04BP538 Cotonou-Rep.Benin
Office : (+229) 95-88-89-64
Office Cel : (+229) 62-55-24-13
Email : info@allinone-benin.com ; info@allinone-plus.com
Web : https://www.allinone-benin.com ; Web : https://www.allinone-plus.com

 
Creating positive change by recruiting the doers, thinkers, and makers
 
ALL IN ONE-BENIN is an Equal Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, national origin, disability, protected veteran status, or any other characteristic protected by law.

***
ALL IN ONE-BÉNIN est un employeur d'égalité des chances. Tous les candidats qualifiés recevront la considération pour l'emploi sans égard à la race, la couleur, la religion, le sexe, l'origine nationale, le handicap, le statut d'ancien combattant protégé, ou toute autre caractéristique protégée par la loi.

Official - AIO 
UNCLASSIFIED
