### ISSUE TITLE
I'm experiencing this error:  ImportError: No module named geopy. so i tried installing geopy but i'm getting another error... must be setuid root (Need HELP)

### ISSUE THREAD

**Issue by rkallon** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#134]

**Comment by t4nk1252** [comment]
I do not believe this works anymore. I keep getting the same error no matter how many fixes I attempt. I tried install geopy separately but I keep getting the same error when I try to install it.
Traceback (most recent call last):
  File "/home/tank/Osintgram/main.py", line 3, in <module>
    from src.Osintgram import Osintgram
  File "/home/tank/Osintgram/src/Osintgram.py", line 13, in <module>
    from geopy.geocoders import Nominatim
ImportError: cannot import name 'Nominatim' from 'geopy.geocoders' (/usr/local/lib/python3.9/dist-packages/geopy/geocoders/__init__.py)
