### ISSUE TITLE
bsdtar: Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by JustinGibbons** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#161]
Hello,

I am attempting to set up the virtual machine on a 32-bit box running Ubuntu 12.04. I have installed Virtualbox 4.2 and Vagrant 1.20 and replaced precise64 with precise32 in the Vagrantfile. When I run vagrant up I get the following output:

Bringing machine 'default' up with 'virtualbox' provider...
[default] Box 'precise32' was not found. Fetching box from specified URL for
the provider 'virtualbox'. Note that if the URL does not have
a box for this provider, you should interrupt Vagrant now and add
the box yourself. Otherwise Vagrant will attempt to download the
full box prior to discovering this error.
Downloading or copying the box...
Extracting box...e: 0/s, Estimated time remaining: --:--:--)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format

Any assistance is appreciated.

**Comment by ttguy** [comment]
I had the same error trying to bring up an oracle virtual box with vagrant.  And if I ran "sudo vagrant up"  instead of just "vagrant up" the problem went away
