### ISSUE TITLE
The guest machine entered an invalid state while waiting for it to boot

### ISSUE THREAD

**Issue by JustinGibbons** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#166]
Hello,

I'm running Ubuntu 12.04 on a Dell Inspiron 700m with Vagrant 1.52 and VirtualBox 4.3.10 installed. When  I run `vagrant up` I get the following output: 

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'precise32'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: Mining-the-Social-Web-2nd-Edition_default_1397154804406_82521
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
    default: 8888 => 8888 (adapter 1)
    default: 5000 => 5000 (adapter 1)
    default: 27017 => 27017 (adapter 1)
    default: 27018 => 27018 (adapter 1)
    default: 27019 => 27019 (adapter 1)
    default: 28017 => 28017 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.
Here is a screen shot from VirtualBox:

![screenshot - 04102014 - 02 44 03 pm](https://cloud.githubusercontent.com/assets/5413270/2671876/30227d5e-c0e0-11e3-87b0-5cdfaa3a82f6.png)

This problem as been associated with virtualization not being enabled in BIOS: https://github.com/protobox/protobox/issues/13

However, I can't find an option to enable virtualization in my BIOS and I don't think there is one since my computer is about 10 years old.

Do you think that my computer is too old to run VirtualBox?

Thank you

**Comment by enriquezrene** [comment]
I solved the problem using my latest OS version:
http://enriquezrene.com/home/index.php/devops/vagrant
