### ISSUE TITLE
CH1 EX5

### ISSUE THREAD

**Issue by roamer13** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#201]
Hi, 
I am having similar issues running Ex 5 in Ch 1 as described here:
https://github.com/ptwobrussell/Mining-the-Social-Web/issues/71
Specifically, after the first time though the loop, the loop terminates.  For example I get an additional 100 items when the count is set to 100 (i.e., 200 items in total). This also happens when I set the count to different values. E.g. when I set the count to 10, I get 20 items in total and the loop terminates after the first time through. Any help is much appreciated!
Thanks!

**Comment by ptwobrussell** [comment]
Fixed by #249
