### ISSUE TITLE
Ipython was working, once, now it stopped

### ISSUE THREAD

**Issue by dlbrooks87** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#267]
Everything worked and when I connected to the localhost:8888 with my browser I saw everything. Then it disconnected, and no matter how many times I destroy / up/ provision / reload it won't come back and I keep getting errors on chef childconverge. 

No one answered any of my other tickets but I do have hope that someone is actually out there.

**Comment by Cornellio** [comment]
Why open so many tickets?  It should be a single issue.

You don't offer enough information. What have you tried so far? Did the Chef recipes run without error? What listening ports are running in the VM?

`sudo netstat -tnap` 

Did you setup the environment in the VM as listed in other threads? e.g,

`sudo ln -s /usr/bin/python /bin/python`

Check python:

`python --version`

Then `exit` from VM and from your local machine:

`vagrant reload`
`vagrant provision`

And monitor results of Chef recipes near the end.
