### ISSUE TITLE
VM failed to boot while Vagrant up

### ISSUE THREAD

**Issue by n00bc0der** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#271]
C:\Users\John\Mining-the-Social-Web-2nd-Edition>vagrant destroy
    default: Are you sure you want to destroy the 'default' VM? [y/N] y
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
==> default: Running cleanup tasks for 'chef_solo' provisioner...

C:\Users\John\Mining-the-Social-Web-2nd-Edition>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'precise64'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: Mining-the-Social-Web-2nd-Edition_defau
lt_1431447430805_13646
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8888 => 8888 (adapter 1)
    default: 5000 => 5000 (adapter 1)
    default: 27017 => 27017 (adapter 1)
    default: 27018 => 27018 (adapter 1)
    default: 27019 => 27019 (adapter 1)
    default: 28017 => 28017 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

This is the initial message that I got when running vagrant up.

After launching the GUI and increasing the RAM allocation, the VM seemed to be able to boot but gets stuck by timing out as shown below. 

C:\Users\John\Mining-the-Social-Web-2nd-Edition>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8888 => 8888 (adapter 1)
    default: 5000 => 5000 (adapter 1)
    default: 27017 => 27017 (adapter 1)
    default: 27018 => 27018 (adapter 1)
    default: 27019 => 27019 (adapter 1)
    default: 28017 => 28017 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

I made sure my Intel Virtualization is enabled at BIOS and cannot seem to work. I also tried multiple vagrant destroys and up with no results.

Help!

**Comment by n00bc0der** [comment]
So apparently a couple of things happened.

1. VT-x was not really enabled.

This is proven when you select your VM Virtual Box, Settings > System > Acceleration.
If acceleration is grayed out, it means somehow it does not detect VT-x being enabled. 
A full shutdown after enabling VT-x solved my issue.

2. Because VT-x was not enabled, I was not able to launch my VM in a Ubuntu 64 bit.

I am not expert but although I was able to run my VM, it somehow turned to a 32 bit, which I guess cause the failed connections.

Solution: Enable VT-x/Intel Virtualization through BIOS. Save changes and reboot. In windows, perform a full shut down. Vagrant destroy any VMs, vagrant up to create new VM with correct settings.

Hope this helps.

**Comment by Evaderei** [comment]
I have the same problem even after enabling VT-x. Any idea of what to do?
