### ISSUE TITLE
LinkedIn API changed Terms of Service

### ISSUE THREAD

**Issue by nicholasjackson827** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#272]
[As seen here,](https://developer.linkedin.com/support/developer-program-transition) LinkedIn just change its terms of service so that getting connections is no longer a possibility without going through a long application process. Any suggestions for a way around this? Or try to get the permissions by submitting the application?

EDIT: Here's the code I'm using that gets me a 403 error:

    from linkedin import linkedin
	import json

	application = linkedin.LinkedInApplication(token='')
	connections = application.get_connections(selectors=['headline', 'first-name', 'last-name'])
	print json.dumps(connections, indent=1)

**Comment by ptwobrussell** [comment]
I haven't re-run all of the examples to check, but from my quick read of
the changes is that the content for Chapter 3 should still work given that
1) most of the key examples are built from a CSV download that's not part
of the API and 2) the few examples that shows the programmatic API are
built from just grabbing the authorized user's connections and basic
profiles. If I'm missing something there, though, please let me know.

Where I think the challenge will be for folks building more robust
applications is with the application process, as you've pointed out. This
process will ultimately create non-trivial friction that encourages people
to tinker around with the API, which might make creating and maintaining
3rd party libraries like python-linkedin more difficult.

**Comment by nicholasjackson827** [comment]
The examples do still work with the CSV file, but just in case anyone tried to get their connections (or groups, invitations, etc.) via the API, I wanted to put this out there.

Thanks for the response!

**Comment by mmeloon** [comment]
@ptwobrussell, just to clarify: you cannot grab information about the authorized user's connections through the API anymore. The CSV file will still have that information, so your examples can run with that. But unfortunately, your Comment #2 is not correct.
