### ISSUE TITLE
I can not vagrant up

### ISSUE THREAD

**Issue by Bashir3** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#310]
Hi,
I use vagrant up command as the instruction says. However, when it comes to unpacking necessary files from the source, the operation is interrupted by the following message:
"An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again." and There is not any message.
I have downloaded the precise64.box manually and change the source in Vagrantfile. However, it does not work from my hardware either.
Please tell me what to do.

**Comment by rreben** [comment]
Please post the whole log file with this issue.

I made a fork, with some adjustments. It is working for me (Windows 7, OSX and it is reported to work with Windows 10, see issue #304). https://github.com/rreben/Mining-the-Social-Web-2nd-Edition

This fork uses another virtual mashine (ubuntu 14), because I observed some errors with precise64.box.

Please make sure you start from scratch. Use `vagrant destroy` till you can log in to your guest mashine with `vagrant ssh`

**Comment by Bashir3** [comment]
Dear Rupert,
Thank you for your response. As I understand, I do not have the built-in
SSH utility. Therefore I do not have proper SSH key. And There is a need
for ssh private key for vagrant up. I am not a developer and my information
is low about git hub.

Regards.


2016-09-26 23:13 GMT+03:30 Rupert Rebentisch <notifications@github.com>:

**Comment by rreben** [comment]
The whole set up is two step process.
1. A virtual mashine is set up as a "guest" on your "host" computer
2. this virtual guest is then provisioned (all the python stuff is installed)
In fact you need the ssh-key mechanism to log in to your virtual guest mashine. If everything runs smothely that however should be transparent to you. However as you encounter some problems, I would need to know, whether the guest mashine is up and running.

I would need to have the log files. Please repeat the whole process. Do a `vagrant destroy`. After that then do a `vagrant up` get the log information. You can grab this either per copy paste or you can redirect the output to a file like so `vagrant up > some.log 2> some_error.log`

You are on windows or Mac?

**Comment by Bashir3** [comment]
Hi,
Yes, I am on windows. I create ssh key and it works on git hub well.
However, the problem exists. I've got the following message:
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find
and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error:


I also save the error to a log file as you said. It has been attached to
the mail, but it does have the same sentences which I have written above,
no more.

Thank you for your attention.
Regards,
Bashir






2016-09-28 21:44 GMT+03:30 Rupert Rebentisch <notifications@github.com>:

**Comment by rreben** [comment]
Can you post the log file. I just got a short notification e-mail, without any attachements. Please Attach the log files on the github site. 
https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition under issue #310.

What I can see is, that vagrant and virtualbox are working. However vagrant is not able to download the ubuntu-image for your guestbox.

I just tried it a couple of minutes ago. The image is still on hashicorp.com and it is accessible. See image / screen shot. You should see the step "importing base box". This step might take at least a couple of minuntes up to an hour or so. You will see a progress indicator.

![learn-how-to-code_ _-bash_ _160x50](https://cloud.githubusercontent.com/assets/4026131/18932311/1c1df7d6-85d0-11e6-98cb-f212d5acc228.png)

If this step is not successful, then the whole process is broken. So keep on trying to come to the point where you see "importing base box". As it is not the hashicorp url, there might be issues with your environment. Is there a firewall / or a proxy that might block the download? Are there any hints in your network errors in your logs?

Also it might be necessary that you install a few additional things on your windows. I can't help you with this, cause I am on a Mac. But I found something here:
https://github.com/mitchellh/vagrant/issues/6754

Or updating vagrant and virtual box. Look at this:
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/354

What are your versions of windows, vagrant or virtual box? I am on vagrant 1.8.5

`vagrant --version`

Will show up the version. Please attach full logs with this issue.

**Comment by Bashir3** [comment]
Dear Rupert,
I use the code below and it seems working:

cp /mingw64/bin/curl.exe /c/HashiCorp/Vagrant/embedded/bin/curl.exe

Thank you,

Regards



2016-09-29 0:49 GMT+03:30 Rupert Rebentisch <notifications@github.com>:

**Comment by rreben** [comment]
So if everything is set, please close the issue on github (star for the fork-repository would be great).
